name: iOS Workflow

on:
  push:
    branches: [ ci_cd ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Archive Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-app-$GITHUB_SHA
          path: /Users/runner/work/flutter-sample/flutter-sample/build/ios/iphoneos/

#      - name: Deploy to Apple App Store
#        uses: codecov/codecov-action@v1
#        with:
#          name: 'Upload to App Store Connect'
#          flags: fail_ci_if_error
#          files: ./build/ios/archive/Runner.xcarchive/Products/Applications/Runner.ipa
#          token: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
